### ISSUE TITLE
Doesn't run/exits with error

### ISSUE THREAD

**Issue by gpopescu** [host-anshu/lint-playbook#7]
Have tried installing via both methods, upon running the playbook linter, it fails with an error:

installed via python setup.py install:
Traceback (most recent call last):
  File "/usr/local/bin/lint-pbook", line 4, in <module>
    __import__('pkg_resources').run_script('LintPlaybook==0.1.dev1', 'lint-pbook')
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 661, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1441, in run_script
    exec(code, namespace, namespace)
  File "/Library/Python/2.7/site-packages/LintPlaybook-0.1.dev1-py2.7.egg/EGG-INFO/scripts/lint-pbook", line 19, in <module>
    main()
  File "/Library/Python/2.7/site-packages/LintPlaybook-0.1.dev1-py2.7.egg/EGG-INFO/scripts/lint-pbook", line 15, in main
    obj.run()
  File "/Library/Python/2.7/site-packages/LintPlaybook-0.1.dev1-py2.7.egg/linter/runner.py", line 68, in run
    self.run_pbook()
  File "/Library/Python/2.7/site-packages/LintPlaybook-0.1.dev1-py2.7.egg/linter/utils/__init__.py", line 21, in decorate
    return meth(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/LintPlaybook-0.1.dev1-py2.7.egg/linter/runner.py", line 46, in run_pbook
    obj.run()
  File "/usr/local/lib/python2.7/site-packages/ansible/cli/playbook.py", line 122, in run
    results = pbex.run()
  File "/usr/local/lib/python2.7/site-packages/ansible/executor/playbook_executor.py", line 156, in run
    result = self._tqm.run(play=play)
  File "/usr/local/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 291, in run
    play_return = strategy.run(iterator, play_context)
  File "/usr/local/lib/python2.7/site-packages/ansible/plugins/strategy/linear.py", line 325, in run
    results += self._wait_on_pending_results(iterator)
  File "/usr/local/lib/python2.7/site-packages/ansible/plugins/strategy/__init__.py", line 712, in _wait_on_pending_results
    results = self._process_pending_results(iterator)
  File "/usr/local/lib/python2.7/site-packages/ansible/plugins/strategy/__init__.py", line 117, in inner
    results = func(self, iterator, one_pass=one_pass, max_passes=max_passes)
  File "/usr/local/lib/python2.7/site-packages/ansible/plugins/strategy/__init__.py", line 645, in _process_pending_results
    self._tqm.send_callback('v2_runner_on_ok', task_result)
  File "/usr/local/lib/python2.7/site-packages/interceptor.py", line 61, in trivial
    run_advices('before')
  File "/usr/local/lib/python2.7/site-packages/interceptor.py", line 59, in run_advices
    impl(self, method, extra_arg, *arg, **kw)
  File "/Library/Python/2.7/site-packages/LintPlaybook-0.1.dev1-py2.7.egg/linter/rules/undefinedVar.py", line 98, in method
    errors["setup"].add("Host %s: %s: %s" % (_host.name, state, _result["msg"]))
KeyError: 'msg'

installed via pip:
Traceback (most recent call last):
  File "/usr/local/bin/lint-pbook", line 79, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/local/bin/lint-pbook", line 16, in main
    return obj.run()
  File "/usr/local/lib/python2.7/site-packages/linter/runner.py", line 59, in run
    self.run_pbook()
  File "/usr/local/lib/python2.7/site-packages/linter/utils/__init__.py", line 19, in decorate
    return meth(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/linter/runner.py", line 45, in run_pbook
    obj.run()
  File "/usr/local/lib/python2.7/site-packages/ansible/cli/playbook.py", line 122, in run
    results = pbex.run()
  File "/usr/local/lib/python2.7/site-packages/ansible/executor/playbook_executor.py", line 156, in run
    result = self._tqm.run(play=play)
  File "/usr/local/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 291, in run
    play_return = strategy.run(iterator, play_context)
  File "/usr/local/lib/python2.7/site-packages/ansible/plugins/strategy/linear.py", line 458, in run
    return super(StrategyModule, self).run(iterator, play_context, result)
  File "/usr/local/lib/python2.7/site-packages/interceptor.py", line 61, in trivial
    run_advices('before')
  File "/usr/local/lib/python2.7/site-packages/interceptor.py", line 59, in run_advices
    impl(self, method, extra_arg, *arg, **kw)
  File "/usr/local/lib/python2.7/site-packages/linter/rules/undefinedVar.py", line 55, in method
    _worker_prc, _main_q, _rslt_q = _worker
TypeError: 'WorkerProcess' object is not iterable

**Comment by host-anshu** [comment]
@gpopescu Thanks for bringing this up! I see that a backward incompatible **ansible** fails this experimental setup that was done about 3 years back. Do you need a specific version of ```ansible```? This experimental setup was tested with versions ```ansible==2.0``` and ```ansible==2.0.2```.

Probably, I should update **README** with this break and fix the dependency to install the supported **ansible** version.

**Comment by gpopescu** [comment]
ah yeah im on ansible/ansible-playbook 2.8.0, so probably a bunch of differences there
